// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	jwtutils "github.com/huypham67/bookmark-service/pkg/jwtutils"
	mock "github.com/stretchr/testify/mock"
)

// TokenValidator is an autogenerated mock type for the TokenValidator type
type TokenValidator struct {
	mock.Mock
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *TokenValidator) ValidateToken(tokenString string) (*jwtutils.CustomClaims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *jwtutils.CustomClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*jwtutils.CustomClaims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *jwtutils.CustomClaims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwtutils.CustomClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenValidator creates a new instance of TokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenValidator {
	mock := &TokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
