# Project Metadata
sonar.organization=huypham67
sonar.projectKey=huypham67_bookmark-service
sonar.projectName=bookmark-service
sonar.projectVersion=1.0

# Scope & Encoding
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*_test.go,**/vendor/**,**/mocks/**,docs/**,bin/**,coverage_report/**,**/logger/**,**/redis/**

# Tests Localization
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**,**/mocks/**

# Quality Gate & Coverage Integration
sonar.go.coverage.reportPaths=coverage_report/coverage.out
sonar.qualitygate.wait=true