// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/huypham67/bookmark-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CountByUserID provides a mock function with given fields: ctx, userID
func (_m *Repository) CountByUserID(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *Repository) Create(ctx context.Context, _a1 *model.Bookmark) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Bookmark) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id, userID
func (_m *Repository) Delete(ctx context.Context, id string, userID string) (int64, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginatedByUserID provides a mock function with given fields: ctx, userID, offset, limit, sort
func (_m *Repository) GetPaginatedByUserID(ctx context.Context, userID string, offset int64, limit int64, sort string) ([]*model.Bookmark, error) {
	ret := _m.Called(ctx, userID, offset, limit, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginatedByUserID")
	}

	var r0 []*model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) ([]*model.Bookmark, error)); ok {
		return rf(ctx, userID, offset, limit, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) []*model.Bookmark); ok {
		r0 = rf(ctx, userID, offset, limit, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, string) error); ok {
		r1 = rf(ctx, userID, offset, limit, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetURLByCode provides a mock function with given fields: ctx, code
func (_m *Repository) GetURLByCode(ctx context.Context, code string) (string, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetURLByCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, userID, updates
func (_m *Repository) Update(ctx context.Context, id string, userID string, updates *model.Bookmark) (int64, error) {
	ret := _m.Called(ctx, id, userID, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.Bookmark) (int64, error)); ok {
		return rf(ctx, id, userID, updates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.Bookmark) int64); ok {
		r0 = rf(ctx, id, userID, updates)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *model.Bookmark) error); ok {
		r1 = rf(ctx, id, userID, updates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
