// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	response "github.com/huypham67/bookmark-service/internal/dto/response"
	mock "github.com/stretchr/testify/mock"
)

// HealthCheckService is an autogenerated mock type for the HealthCheckService type
type HealthCheckService struct {
	mock.Mock
}

// GetStatus provides a mock function with given fields: ctx
func (_m *HealthCheckService) GetStatus(ctx context.Context) response.HealthCheckResponse {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 response.HealthCheckResponse
	if rf, ok := ret.Get(0).(func(context.Context) response.HealthCheckResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(response.HealthCheckResponse)
	}

	return r0
}

// NewHealthCheckService creates a new instance of HealthCheckService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheckService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheckService {
	mock := &HealthCheckService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
