// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/huypham67/bookmark-service/internal/model"
	mock "github.com/stretchr/testify/mock"

	request "github.com/huypham67/bookmark-service/internal/dto/request"
)

// Profile is an autogenerated mock type for the Profile type
type Profile struct {
	mock.Mock
}

// GetUserInfo provides a mock function with given fields: ctx, userID
func (_m *Profile) GetUserInfo(ctx context.Context, userID string) (*model.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserInfo provides a mock function with given fields: ctx, userID, req
func (_m *Profile) UpdateUserInfo(ctx context.Context, userID string, req request.UpdateUserRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.UpdateUserRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProfile creates a new instance of Profile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfile(t interface {
	mock.TestingT
	Cleanup(func())
}) *Profile {
	mock := &Profile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
