// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	response "github.com/huypham67/bookmark-management/internal/dto/response"
	mock "github.com/stretchr/testify/mock"
)

// HealthCheck is an autogenerated mock type for the HealthCheck type
type HealthCheck struct {
	mock.Mock
}

type HealthCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthCheck) EXPECT() *HealthCheck_Expecter {
	return &HealthCheck_Expecter{mock: &_m.Mock}
}

// GetStatus provides a mock function with no fields
func (_m *HealthCheck) GetStatus() (response.HealthCheckResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 response.HealthCheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (response.HealthCheckResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() response.HealthCheckResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(response.HealthCheckResponse)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HealthCheck_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type HealthCheck_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *HealthCheck_Expecter) GetStatus() *HealthCheck_GetStatus_Call {
	return &HealthCheck_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *HealthCheck_GetStatus_Call) Run(run func()) *HealthCheck_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HealthCheck_GetStatus_Call) Return(_a0 response.HealthCheckResponse, _a1 error) *HealthCheck_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HealthCheck_GetStatus_Call) RunAndReturn(run func() (response.HealthCheckResponse, error)) *HealthCheck_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewHealthCheck creates a new instance of HealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheck {
	mock := &HealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
