// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	request "github.com/huypham67/bookmark-management/internal/dto/request"
	mock "github.com/stretchr/testify/mock"
)

// Link is an autogenerated mock type for the Link type
type LinkService struct {
	mock.Mock
}

// ShortenURL provides a mock function with given fields: _a0
func (_m *LinkService) ShortenURL(_a0 request.ShortenURLRequest) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ShortenURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(request.ShortenURLRequest) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(request.ShortenURLRequest) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(request.ShortenURLRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLinkService creates a new instance of LinkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkService {
	mock := &LinkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
