// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// LinkHandler is an autogenerated mock type for the LinkHandler type
type LinkHandler struct {
	mock.Mock
}

// ShortenURL provides a mock function with given fields: c
func (_m *LinkHandler) ShortenURL(c *gin.Context) {
	_m.Called(c)
}

// NewLinkHandler creates a new instance of LinkHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkHandler {
	mock := &LinkHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
