// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LinkRepository is an autogenerated mock type for the Link type
type LinkRepository struct {
	mock.Mock
}

// CheckExists provides a mock function with given fields: code
func (_m *LinkRepository) CheckExists(code string) (bool, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for CheckExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveLink provides a mock function with given fields: code, url, exp
func (_m *LinkRepository) SaveLink(code string, url string, exp int64) error {
	ret := _m.Called(code, url, exp)

	if len(ret) == 0 {
		panic("no return value specified for SaveLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64) error); ok {
		r0 = rf(code, url, exp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLinkRepository creates a new instance of LinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkRepository {
	mock := &LinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
