// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bookmark "github.com/huypham67/bookmark-service/internal/dto/bookmark"

	mock "github.com/stretchr/testify/mock"

	model "github.com/huypham67/bookmark-service/internal/model"

	servicebookmark "github.com/huypham67/bookmark-service/internal/service/bookmark"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *Service) Create(ctx context.Context, userID string, req bookmark.CreateBookmarkRequest) (*model.Bookmark, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bookmark.CreateBookmarkRequest) (*model.Bookmark, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bookmark.CreateBookmarkRequest) *model.Bookmark); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bookmark.CreateBookmarkRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, userID, bookmarkID
func (_m *Service) Delete(ctx context.Context, userID string, bookmarkID string) error {
	ret := _m.Called(ctx, userID, bookmarkID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, bookmarkID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, userID, req
func (_m *Service) List(ctx context.Context, userID string, req *bookmark.ListBookmarksRequest) ([]*model.Bookmark, *servicebookmark.PaginationResult, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Bookmark
	var r1 *servicebookmark.PaginationResult
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *bookmark.ListBookmarksRequest) ([]*model.Bookmark, *servicebookmark.PaginationResult, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *bookmark.ListBookmarksRequest) []*model.Bookmark); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *bookmark.ListBookmarksRequest) *servicebookmark.PaginationResult); ok {
		r1 = rf(ctx, userID, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*servicebookmark.PaginationResult)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *bookmark.ListBookmarksRequest) error); ok {
		r2 = rf(ctx, userID, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, userID, bookmarkID, req
func (_m *Service) Update(ctx context.Context, userID string, bookmarkID string, req bookmark.UpdateBookmarkRequest) error {
	ret := _m.Called(ctx, userID, bookmarkID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bookmark.UpdateBookmarkRequest) error); ok {
		r0 = rf(ctx, userID, bookmarkID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
