// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Importer is an autogenerated mock type for the Importer type
type Importer struct {
	mock.Mock
}

// Import provides a mock function with given fields: ctx, userID, r
func (_m *Importer) Import(ctx context.Context, userID string, r io.Reader) error {
	ret := _m.Called(ctx, userID, r)

	if len(ret) == 0 {
		panic("no return value specified for Import")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, userID, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewImporter creates a new instance of Importer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Importer {
	mock := &Importer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
