// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteCacheByFieldKey provides a mock function with given fields: ctx, hashKey, fieldKey
func (_m *Repository) DeleteCacheByFieldKey(ctx context.Context, hashKey string, fieldKey string) error {
	ret := _m.Called(ctx, hashKey, fieldKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCacheByFieldKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, hashKey, fieldKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCacheByHashKey provides a mock function with given fields: ctx, hashKey
func (_m *Repository) DeleteCacheByHashKey(ctx context.Context, hashKey string) error {
	ret := _m.Called(ctx, hashKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCacheByHashKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, hashKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCache provides a mock function with given fields: ctx, hashKey, fieldKey
func (_m *Repository) GetCache(ctx context.Context, hashKey string, fieldKey string) ([]byte, error) {
	ret := _m.Called(ctx, hashKey, fieldKey)

	if len(ret) == 0 {
		panic("no return value specified for GetCache")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return rf(ctx, hashKey, fieldKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, hashKey, fieldKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, hashKey, fieldKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetCache provides a mock function with given fields: ctx, hashKey, fieldKey, value, ttl
func (_m *Repository) SetCache(ctx context.Context, hashKey string, fieldKey string, value []byte, ttl time.Duration) error {
	ret := _m.Called(ctx, hashKey, fieldKey, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, time.Duration) error); ok {
		r0 = rf(ctx, hashKey, fieldKey, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
