basePath: /api/v1
definitions:
  github_com_huypham67_bookmark-management_internal_model.HealthCheckResponse:
    properties:
      instance_id:
        type: string
      message:
        type: string
      service_name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the Bookmark Management service.
  title: Bookmark Management API
  version: "1.0"
paths:
  /health-check:
    get:
      consumes:
      - application/json
      description: Check application health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_huypham67_bookmark-management_internal_model.HealthCheckResponse'
      summary: Health Check
      tags:
      - health
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
