basePath: /api
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  github_com_huypham67_bookmark-service_internal_dto_request.ShortenURLRequest:
    properties:
      exp:
        minimum: 0
        type: integer
      url:
        type: string
    required:
    - url
    type: object
  github_com_huypham67_bookmark-service_internal_dto_response.HealthCheckResponse:
    properties:
      instance_id:
        type: string
      message:
        type: string
      service_name:
        type: string
    type: object
  github_com_huypham67_bookmark-service_internal_dto_response.ShortenURLResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is the API documentation for the Bookmark Management service.
  title: Bookmark Management API
  version: "1.0"
paths:
  /health-check:
    get:
      consumes:
      - application/json
      description: Check application health status and Redis connection
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_huypham67_bookmark-service_internal_dto_response.HealthCheckResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_huypham67_bookmark-service_internal_dto_response.HealthCheckResponse'
      summary: Health Check
      tags:
      - health
  /v1/links/redirect/{code}:
    get:
      consumes:
      - application/json
      description: Redirect user to the original URL based on the shortened code
      parameters:
      - description: Shortened code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "301":
          description: Redirect successful
        "404":
          description: Short link not found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Redirect to Original URL
      tags:
      - links
  /v1/links/shorten:
    post:
      consumes:
      - application/json
      description: Create a shortened URL code and save it to Redis
      parameters:
      - description: URL to shorten
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_huypham67_bookmark-service_internal_dto_request.ShortenURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Shorten URL generated successfully
          schema:
            $ref: '#/definitions/github_com_huypham67_bookmark-service_internal_dto_response.ShortenURLResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Shorten URL
      tags:
      - links
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
