name: cd-pipeline

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Application
        working-directory: /opt/bookmark-system
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          set -e

          echo "TAG=${IMAGE_TAG}" > .env
          
          echo "::notice title=CD Status::🚀 Deploying with image tag: [${IMAGE_TAG}]"

          echo "Pulling image: bookmark-service:${IMAGE_TAG}..."
          docker compose pull bookmark-service

          echo "Recreating service..."
          docker compose up -d --force-recreate bookmark-service

          echo "Cleaning up unused images..."
          docker image prune -f --filter "until=24h"

          echo "✅ Deployment completed successfully"
