name: ci-pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: "bookmark-service"
  COVERAGE_THRESHOLD: 80

jobs:
  ci-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests and check coverage
        run: make docker-test
        env:
          COVERAGE_THRESHOLD: ${{ env.COVERAGE_THRESHOLD }}

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        run: make docker-login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: make docker-build-push
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GIT_SHA: ${{ github.sha }}
          GIT_EVENT_NAME: ${{ github.event_name }}
          GIT_REF_TYPE: ${{ github.ref_type }}
          GIT_REF_NAME: ${{ github.ref_name }}

  trigger-deployment:
    name: Trigger CD
    needs: ci-flow

    if: github.event_name != 'pull_request' && github.ref_name == 'main'

    uses: ./.github/workflows/cd.yaml

    with:
      target_env: staging
      image_tag: ${{ github.sha }}